prefixes:
  - pattern: "(Stání pro karavan|obytný přívěs|mikrobus|nákladní auto)"
    label: "K"
  - pattern: "Přívěsný vozík"
    label: "V"
  - pattern: "Stan malý"
    label: "A"
  - pattern: "Přípojka elektrického proudu"
    label: "E"
    
blacklist:
 - "chatka"

year: 2025