prefixes:
  - pattern: "Přívěsný vozík"
    label: "V"
  - pattern: "Stan malý"
    label: "A"
  - pattern: "Přípojka elektrického proudu"
    label: "E"

special:
  - pattern: "(Stání pro karavan|obytný přívěs|mikrobus|nákladní auto)"
    label: "K"
    identifier: "P"

blacklist:
  - "chatka"

year: 2025