prefixes:
  - pattern: "Přístřešek/markýza do 9 m2"
    label: "P"
  - pattern: "Přístřešek/markýza nad 9 m2"
    label: "R"
  - pattern: "Příplatek za spaní v osobním autě (= do 1,7t)"
    label: "T"
  - pattern: "Příplatek za spaní v dodávce apod. (nad 1,7t)"
    label: "U"
  - pattern: "Přívěsný vozík"
    label: "V"
  - pattern: "Hamaka"
    label: "H"
  - pattern: "Stan malý (4 m2)"
    label: "A"
  - pattern: "Stan malý (4 m2)"
    label: "B"
  - pattern: "Stan malý (4 m2)"
    label: "C"
  - pattern: "Přípojka elektrického proudu pro stany"
    label: "E"


special:
  - pattern: "(Stání pro karavan|obytný přívěs|mikrobus|nákladní auto)"
    label: "K"
    identifier: "P"

blacklist:
  - "kafksafkhalkf"

year: 2025