#konfigurace prefixu
prefixes:
  - pattern: "(Stání pro karavan|obytný přívěs|mikrobus|nákladní auto)"
    label: "K"
  - pattern: "(Přívěsný vozík)"
    label: "V"
  - pattern: "Stan"
    label: "A"

year: 2026
