year: 2024
prefixes:
  - pattern: "(Stání pro karavan|obytný přívěs|mikrobus|nákladní auto)"
    prefix: "K"
  - pattern: "(Přípojka elektrického proudu)"
    prefix: "E"
  - pattern: "(Stání pro osobní auto)"
    prefix: "A"
  - pattern: "(Stanování|táborová plocha)"
    prefix: "T"
default_prefix: "N"