rules:
  - match: "stan malý"
    prefix: "A"
  - match: "stan střední"
    prefix: "B"
  - match: "stan velký"
    prefix: "C"
  - match: "karavan"
    prefix: "K"
  - match: "přístřešek malý"
    prefix: "P"
  - match: "přístřešek velký"
    prefix: "P9"
  - match: "spaní v autě do 1,7tun"
    prefix: "A1"
  - match: "spaní v autě nad 1,7tun"
    prefix: "A2"
  - match: "vozík"
    prefix: "V"
  - match: "spaní pod širákem"
    prefix: "H"
  - match: "elektřina"
    prefix: "E"
year: 2024
